// Data sourced from: “Prefixes and Suffixes” (Medical Terminology for Healthcare Professions, UWF Pressbooks).
// Book license: CC BY 4.0. See: https://pressbooks.uwf.edu/medicalterminology/chapter/prefixes-and-suffixes/

window.TERMS = {
  prefixes: {
    "Common Prefixes": [
      { part: "A-, An-", meaning: "Without; Lacking", example: "Anemia (low red blood cell count)" },
      { part: "Andr/o-", meaning: "Male", example: "Androgen (male sex hormone)" },
      { part: "Anti-", meaning: "Against", example: "Anticholinergic drugs (block acetylcholine)" },
      { part: "Auto-", meaning: "Self", example: "Autocrine (acts on same cell)" },
      { part: "Bio-", meaning: "Life", example: "Biology (study of life)" },
      { part: "Chem/o-", meaning: "Chemistry", example: "Chemotherapy (drug treatment for cancer)" },
      { part: "Contra-", meaning: "Against", example: "Contraception (prevents pregnancy)" },
      { part: "Cyt/o-", meaning: "Cell", example: "Cytokine (cell signaling protein)" },
      { part: "Dis-", meaning: "Separation; Taking apart", example: "Dissection (cutting apart tissues)" },
      { part: "Dys-", meaning: "Difficult; Abnormal", example: "Dyspnea (difficulty breathing)" },
      { part: "Eu-", meaning: "Good; Well", example: "Eupnea (normal breathing)" },
      { part: "Fibr/o-", meaning: "Fiber", example: "Fibrosis (scar tissue formation)" },
      { part: "Gluco-, Glyco-", meaning: "Glucose; Sugar", example: "Glycogen (stored form of glucose)" },
      { part: "Gyn/o-, Gynec-", meaning: "Female", example: "Gynecology (female reproductive medicine)" },
      { part: "Hydr/o-", meaning: "Water", example: "Hydrocephalus (CSF buildup in brain)" },
      { part: "Idio-", meaning: "Self; One’s own", example: "Idiopathic (unknown cause)" },
      { part: "Lyso-, Lys-", meaning: "Break down; Destruction; Dissolving", example: "Lysosome (cell digestion organelle)" },
      { part: "Mal-", meaning: "Bad; Abnormal", example: "Malignant (cancerous)" },
      { part: "Myc/o-", meaning: "Fungus", example: "Mycetoma (fungal infection)" },
      { part: "Necr/o-", meaning: "Death", example: "Necrosis (tissue death)" },
      { part: "Neo-", meaning: "New", example: "Neonate (newborn)" },
      { part: "Oxy-", meaning: "Sharp; Acute; Oxygen", example: "Oxytocin (uterine/milk hormone)" },
      { part: "Pan-, Pant/o-", meaning: "All or everywhere", example: "Pancytopenia (low all blood cells)" },
      { part: "Pharmaco-", meaning: "Drug; Medicine", example: "Pharmacist (medication specialist)" },
      { part: "Re-", meaning: "Again; Backward", example: "Rejuvenation (becoming young again)" },
      { part: "Somat/o-, Somatico-", meaning: "Body; Bodily", example: "Somatic cell (body cell)" }
    ],

    "Body Part Prefixes": [
      { part: "Acous/o-", meaning: "Hearing", example: "Acoustic meatus (ear canal)" },
      { part: "Aden/o-", meaning: "Gland", example: "Adenoid (nasopharyngeal lymph tissue)" },
      { part: "Adip/o-", meaning: "Fat", example: "Adipocyte (fat cell)" },
      { part: "Adren/o-", meaning: "Gland", example: "Adrenal cortex (outer adrenal layer)" },
      { part: "Angi/o-", meaning: "Blood vessel", example: "Angioplasty (open a blood vessel)" },
      { part: "Arteri/o-", meaning: "Artery", example: "Arteriole (small artery)" },
      { part: "Arthr/o-", meaning: "Joint", example: "Arthroplasty (joint repair/replacement)" },
      { part: "Bucc/o-", meaning: "Cheek", example: "Buccal cavity (mouth area)" },
      { part: "Bronch/i-", meaning: "Bronchus", example: "Bronchioles (small airways)" },
      { part: "Burs/o-", meaning: "Bursa", example: "Bursa (joint fluid sac)" },
      { part: "Carcin/o-", meaning: "Cancer", example: "Basal cell carcinoma (skin cancer)" },
      { part: "Cardi/o-", meaning: "Heart", example: "Cardiology (study of the heart)" },
      { part: "Cephal/o-", meaning: "Head", example: "Cephalic flexure (head bend in embryo)" },
      { part: "Chol-", meaning: "Bile", example: "Cholesterol (blood lipid)" },
      { part: "Chondri-", meaning: "Cartilage", example: "Chondrosarcoma (cartilage cancer)" },
      { part: "Coron-", meaning: "Heart", example: "Coronary arteries (heart blood vessels)" },
      { part: "Cost-", meaning: "Rib", example: "Costal cartilage (rib cartilage)" },
      { part: "Crani/o-", meaning: "Brain", example: "Cranium (skull)" },
      { part: "Cutane-", meaning: "Skin", example: "Cutaneous (relating to skin)" },
      { part: "Cyst/o-, Cysti-", meaning: "Bladder or sac", example: "Cystoscopy (bladder scope exam)" },
      { part: "Derm-, Dermat/o-", meaning: "Skin", example: "Dermatologist (skin doctor)" },
      { part: "Duoden/o-", meaning: "Duodenum", example: "Duodenitis (duodenum inflammation)" },
      { part: "Gastr-", meaning: "Stomach", example: "Gastrectomy (stomach removal)" },
      { part: "Gloss-", meaning: "Tongue", example: "Glossectomy (tongue removal)" },
      { part: "Hem-, Hema-, Hemat-, Hemo-, Hemat/o-", meaning: "Blood", example: "Hematopoiesis (blood cell formation)" },
      { part: "Hepat/o-, Hepatico-", meaning: "Liver", example: "Hepatic portal system (liver blood route)" },
      { part: "Hist/o-, Histio-", meaning: "Tissue", example: "Histology (study of tissues)" },
      { part: "Hyster/o-", meaning: "Uterus", example: "Hysterectomy (uterus removal)" },
      { part: "Ileo-", meaning: "Ileum", example: "Ileostomy (ileum opening to skin)" },
      { part: "Ischi/o-", meaning: "Ischium", example: "Ischial tuberosity (sit bone)" },
      { part: "Kerat/o-", meaning: "Cornea (eye or skin)", example: "Keratin (structural skin protein)" },
      { part: "Lacrim/o-", meaning: "Tear (from your eyes)", example: "Lacrimal fluid (tears)" },
      { part: "Lact/o-, Lacti-", meaning: "Milk", example: "Lactose (milk sugar)" },
      { part: "Laryng/o-", meaning: "Larynx", example: "Laryngitis (voice box inflammation)" },
      { part: "Lingu/o-", meaning: "Tongue", example: "Lingual tonsil (tonsil at tongue base)" },
      { part: "Lip/o-", meaning: "Fat", example: "Lipolysis (fat breakdown)" },
      { part: "Lymph/o-", meaning: "Lymph", example: "Lymphocyte (white blood cell)" },
      { part: "Mamm-, Mast/o-", meaning: "Breast", example: "Mammary glands (milk-producing glands)" },
      { part: "Mening/o-", meaning: "Meninges", example: "Meningitis (meninges inflammation)" },
      { part: "Muscul/o-", meaning: "Muscle", example: "Musculoskeletal (muscle + skeleton)" },
      { part: "My/o-", meaning: "Muscle", example: "Myocardium (heart muscle layer)" },
      { part: "Myel/o-", meaning: "Spinal cord or bone marrow", example: "Myelin (nerve insulation)" },
      { part: "Nephr/o-", meaning: "Kidney", example: "Nephron (kidney functional unit)" },
      { part: "Neur/i-, Neur/o-", meaning: "Nerve", example: "Neuron (nerve cell)" },
      { part: "Oculo-", meaning: "Eye", example: "Oculomotor nerve (controls eye movement)" },
      { part: "Onco-", meaning: "Tumor; Bulk; Volume", example: "Oncogene (cancer-related gene)" },
      { part: "Onych/o-", meaning: "Fingernail; Toenail", example: "Onychodystrophy (abnormal nail growth)" },
      { part: "Oo-", meaning: "Egg; Ovary", example: "Oocyte (egg cell)" },
      { part: "Oophor/o-", meaning: "Ovary", example: "Oophorectomy (ovary removal)" },
      { part: "Op-, Opt-", meaning: "Vision", example: "Optic nerve (vision nerve)" },
      { part: "Ophthalm/o-", meaning: "Eye", example: "Ophthalmic artery (artery to eye)" },
      { part: "Orchid/o-, Orchio-", meaning: "Testis", example: "Orchidectomy (testis removal)" },
      { part: "Orth/o-", meaning: "Straight; Normal; Correct", example: "Orthostatic (relating to standing)" },
      { part: "Osseo-", meaning: "Bony", example: "Osseous tissue (bone tissue)" },
      { part: "Ossi-", meaning: "Bone", example: "Ossicles (tiny ear bones)" },
      { part: "Ost-, Oste/o-", meaning: "Bone", example: "Osteoporosis (bone density loss)" },
      { part: "Ot/o-", meaning: "Ear", example: "Otolaryngologist (ENT doctor)" },
      { part: "Ovar/i-, Ovario-, Ovi-, Ovo-", meaning: "Ovary", example: "Ovarian follicle (egg-containing sac)" },
      { part: "Phalang-", meaning: "Phalanx", example: "Phalanges (finger/toe bones)" },
      { part: "Pharyng/o-", meaning: "Pharynx; Throat", example: "Pharyngeal tonsil (throat tonsil)" },
      { part: "Phleb/o-", meaning: "Vein", example: "Phlebotomist (draws blood)" },
      { part: "Phren/i-, Phreno-, Phrenico-", meaning: "Diaphragm", example: "Phrenic nerve (nerve to diaphragm)" },
      { part: "Pleur-, Pleur/a-, Pleur/o-", meaning: "Rib, pleura", example: "Pleural cavity (space around lungs)" },
      { part: "Pneum/a-, Pneumat/o-", meaning: "Air; Lung", example: "Pneumonia (lung infection)" },
      { part: "Proct/o-", meaning: "Anus; Rectum", example: "Proctoscopy (rectum scope exam)" },
      { part: "Prostat-", meaning: "Prostate", example: "Prostatectomy (prostate removal)" },
      { part: "Pseudo-", meaning: "False", example: "Pseudostratified (appears layered)" },
      { part: "Psych/o-, Psyche-", meaning: "Mind", example: "Psychiatrist (mental health doctor)" },
      { part: "Radio-", meaning: "Radiation; Radius", example: "Radioisotopes (radioactive atoms)" },
      { part: "Ren/o-", meaning: "Kidney", example: "Renal cortex (outer kidney region)" },
      { part: "Retin-", meaning: "Retina (of the eye)", example: "Retinitis pigmentosa (retinal degeneration)" },
      { part: "Rhin/o-", meaning: "Nose", example: "Rhinoscope (nose scope instrument)" },
      { part: "Salping/o-", meaning: "Tube", example: "Salpingo-oophorectomy (remove tubes/ovaries)" },
      { part: "Sarco-", meaning: "Muscular; Flesh-like", example: "Sarcomere (muscle contractile unit)" },
      { part: "Schiz/o-", meaning: "Split; Cleft", example: "Schizophrenia (psychotic disorder)" },
      { part: "Sclera-, Sclero-", meaning: "Hardness", example: "Sclerosis (tissue hardening)" },
      { part: "Sigmoid/o-", meaning: "Sigmoid colon", example: "Sigmoidoscopy (sigmoid colon scope)" },
      { part: "Sperma-, Spermo-, Spermato-", meaning: "Sperm", example: "Spermatocyte (sperm precursor cell)" },
      { part: "Splen/o-", meaning: "Spleen", example: "Splenomegaly (enlarged spleen)" },
      { part: "Sten/o-", meaning: "Narrowed; Blocked", example: "Stenosis (narrowing)" },
      { part: "Stern-", meaning: "Sternum", example: "Sternoclavicular joint (sternum-clavicle joint)" },
      { part: "Stom/a-, Stomat/o-", meaning: "Mouth", example: "Stomatitis (mouth inflammation)" },
      { part: "Thorac/o-, Thoracico-", meaning: "Chest", example: "Thoracic cavity (chest cavity)" },
      { part: "Thromb/o-", meaning: "Blood clot", example: "Thrombolytic (clot-busting drug)" },
      { part: "Thyr/o-", meaning: "Thyroid gland", example: "Thyroiditis (thyroid inflammation)" },
      { part: "Trache/o-", meaning: "Trachea", example: "Trachealis (muscle of trachea)" },
      { part: "Tympan/o-", meaning: "Eardrum", example: "Tympanic membrane (eardrum)" },
      { part: "Ur/o-", meaning: "Urine", example: "Urologist (urinary tract doctor)" },
      { part: "Vagin-", meaning: "Vagina", example: "Vaginal (relating to vagina)" },
      { part: "Varic/o-", meaning: "Duct; Blood vessel", example: "Varicose veins (enlarged twisted veins)" },
      { part: "Vasculo-", meaning: "Blood vessel", example: "Vasculitis (blood vessel inflammation)" },
      { part: "Ven/o-", meaning: "Vein", example: "Venae cavae (large veins to heart)" },
      { part: "Vertbr-", meaning: "Vertebra; Spine", example: "Vertebral column (spine)" }
    ],

    "Color Prefixes": [
      { part: "Chlor/o-", meaning: "Green", example: "Chlorophyll (green plant pigment)" },
      { part: "Chrom-, Chromato-", meaning: "Color", example: "Chromosome (DNA structure)" },
      { part: "Cyano-", meaning: "Blue", example: "Cyanosis (bluish skin from low oxygen)" },
      { part: "Erythr/o-", meaning: "Red", example: "Erythrocyte (red blood cell)" },
      { part: "Leuk/o-", meaning: "White", example: "Leukocyte (white blood cell)" },
      { part: "Melan/o-", meaning: "Black", example: "Melanin (skin pigment)" }
    ],

    "Physical Property and Shape Prefixes": [
      { part: "Cry/o-", meaning: "Cold", example: "Cryotherapy (cold treatment)" },
      { part: "Elect-", meaning: "Electrical activity", example: "Electrocardiogram (heart electrical tracing)" },
      { part: "Kin/o-, Kine-, Kinesi/o-", meaning: "Movement", example: "Kinetic energy (energy of motion)" },
      { part: "Kyphy/o-", meaning: "Humped", example: "Kyphosis (hunched spine curve)" },
      { part: "Rhabd/o-", meaning: "Rod-shaped; Striated", example: "Rhabdomyosarcoma (skeletal muscle cancer)" },
      { part: "Phot/o-", meaning: "Light", example: "Photoreceptor (light-sensing cell)" },
      { part: "Reticul/o-", meaning: "Net", example: "Reticulocytes (immature red blood cells)" },
      { part: "Scoli/o-", meaning: "Twisted", example: "Scoliosis (sideways spine curve)" },
      { part: "Therm/o-", meaning: "Heat", example: "Thermotherapy (heat treatment)" }
    ],

    "Direction and Position Prefixes": [
      { part: "Ab-, Abs-", meaning: "Away from", example: "Abductor (moves away from midline)" },
      { part: "Ad-", meaning: "Towards", example: "Adductor (moves toward midline)" },
      { part: "Ante-", meaning: "Before; Forward", example: "Antenatal (before birth)" },
      { part: "Circum-", meaning: "Around", example: "Circumcision (foreskin removal)" },
      { part: "Cycl-", meaning: "Circle; Cycle", example: "Cyclic neutropenia (periodic low neutrophils)" },
      { part: "De-", meaning: "Away from; Ending", example: "Dehydration (low body water)" },
      { part: "Dia-", meaning: "Across; Through", example: "Diagnosis (identify disease)" },
      { part: "Ect/o-, Exo-", meaning: "Outer; Outside", example: "Exocrine gland (secretes outward)" },
      { part: "End/o-, Ent-, Enter/o-", meaning: "Within; Inner", example: "Endocrine gland (hormones into blood)" },
      { part: "Epi-", meaning: "Upon; Outside of", example: "Epidermis (outer skin layer)" },
      { part: "Ex-, Extra-", meaning: "Beyond", example: "Expiration (breathing out)" },
      { part: "Infra-", meaning: "Beneath; Below", example: "Infratemporal fossa (space below temple)" },
      { part: "Inter-", meaning: "Between", example: "Interstitial fluid (between cells)" },
      { part: "Intra-", meaning: "Within", example: "Intracellular fluid (inside cells)" },
      { part: "Meso-", meaning: "Middle", example: "Mesoderm (middle embryonic layer)" },
      { part: "Meta-", meaning: "Beyond; Change", example: "Metabolism (chemical processes)" },
      { part: "Para-", meaning: "Alongside; Abnormal", example: "Parathyroid glands (regulate calcium)" },
      { part: "Path/o-", meaning: "Disease", example: "Pathologist (disease specialist)" },
      { part: "Peri-", meaning: "Around", example: "Pericardium (sac around heart)" },
      { part: "Post-", meaning: "Behind; After", example: "Postpartum (after childbirth)" },
      { part: "Pre-", meaning: "Before; In front", example: "Precancerous (before cancer)" },
      { part: "Retro-", meaning: "Backward; Behind", example: "Retroperitoneum (behind peritoneum)" },
      { part: "Sub-", meaning: "Under", example: "Subcutaneous layer (under skin)" },
      { part: "Super-", meaning: "Above", example: "Superior (above)" },
      { part: "Supra-", meaning: "Above; Upon", example: "Supraglottis (above vocal cords)" },
      { part: "Sy-, Syl-, Sym-, Syn-, Sys-", meaning: "Together", example: "Syndrome (group of symptoms)" },
      { part: "Trans-", meaning: "Across; Through", example: "Transdermal (through skin)" }
    ],

    "Quantity Prefixes": [
      { part: "Bi-", meaning: "Two", example: "Biceps (two-headed muscle)" },
      { part: "Brady-", meaning: "Slow", example: "Bradycardia (slow heart rate)" },
      { part: "Diplo-", meaning: "Double", example: "Diploid (two chromosome sets)" },
      { part: "Hemi-", meaning: "Half", example: "Hemihypertrophy (half-body overgrowth)" },
      { part: "Hetero-", meaning: "Other; Different", example: "Heterogeneous (mixed composition)" },
      { part: "Homo-", meaning: "Same", example: "Homozygous genotype (same alleles)" },
      { part: "Hyper-", meaning: "Above; Beyond; Excessive", example: "Hypertension (high blood pressure)" },
      { part: "Hypo-", meaning: "Under; Deficient", example: "Hypotension (low blood pressure)" },
      { part: "Iso-", meaning: "Equal; Like", example: "Isointense (same MRI intensity)" },
      { part: "Macro-", meaning: "Large; Long; Big", example: "Macrophage (large immune cell)" },
      { part: "Mic-, Micro-", meaning: "Small", example: "Microglia (small CNS immune cells)" },
      { part: "Mon-, Mono-", meaning: "One", example: "Monocyte (single-nucleus WBC)" },
      { part: "Olig/o-", meaning: "Few; Little", example: "Oliguria (low urine output)" },
      { part: "Poly-", meaning: "Many; Excessive", example: "Polyuria (excess urination)" },
      { part: "Quadri-", meaning: "Four", example: "Quadriceps (four-headed muscle)" },
      { part: "Semi-", meaning: "Half", example: "Semilunar valves (half-moon valves)" },
      { part: "Tachy-", meaning: "Fast", example: "Tachycardia (fast heart rate)" },
      { part: "Tetra-", meaning: "Four", example: "Tetralogy of Fallot (four heart defects)" },
      { part: "Tri-", meaning: "Three", example: "Triceps (three-headed muscle)" },
      { part: "Uni-", meaning: "One", example: "Unicellular (single-celled)" }
    ]
  },

  suffixes: {
    "Common Suffixes": [
      { part: "-ac", meaning: "Pertaining to", example: "Cardiac (relating to the heart)" },
      { part: "-blast, -blasto, -blastic", meaning: "Bud; Germ", example: "Myeloblast (immature marrow cell)" },
      { part: "-cyte, -cytic", meaning: "Cell", example: "Thrombocyte (platelet)" },
      { part: "-dynia", meaning: "Pain; Swelling", example: "Thoracodynia (chest pain)" },
      { part: "-eal, -ial", meaning: "Pertaining to", example: "Esophageal (relating to esophagus)" },
      { part: "-ectasis", meaning: "Expansion; Dilation", example: "Atelectasis (lung collapse)" },
      { part: "-emia", meaning: "Blood condition", example: "Anemia (low red blood cell count)" },
      { part: "-ia", meaning: "Condition", example: "Hemophilia (bleeding disorder)" },
      { part: "-iasis", meaning: "Condition; Formation of", example: "Psoriasis (chronic skin condition)" },
      { part: "-ism", meaning: "Condition", example: "Hypothyroidism (low thyroid function)" },
      { part: "-ites, -itis", meaning: "Inflammation", example: "Arthritis (joint inflammation)" },
      { part: "-ity", meaning: "Pertaining to", example: "Immunity (ability to resist infection)" },
      { part: "-ium", meaning: "Structure or tissue", example: "Epithelium (lining tissue)" },
      { part: "-lysis, -lytic", meaning: "Break down; Destruction; Dissolving", example: "Osteolytic (bone breakdown)" },
      { part: "-malacia", meaning: "Softening", example: "Osteomalacia (soft bones)" },
      { part: "-megaly", meaning: "Enlargement", example: "Acromegaly (enlarged hands/feet)" },
      { part: "-oid", meaning: "Resembling", example: "Arachnoid trabeculae (web-like strands)" },
      { part: "-oma", meaning: "Tumor", example: "Angiosarcoma (blood vessel cancer)" },
      { part: "-osis", meaning: "Condition; Usually abnormal", example: "Endometriosis (uterine tissue outside uterus)" },
      { part: "-ous", meaning: "Pertaining to", example: "Aqueous (watery)" },
      { part: "-pathy", meaning: "Disease", example: "Lymphadenopathy (enlarged lymph nodes)" },
      { part: "-penia", meaning: "Deficiency; Lack of", example: "Thrombocytopenia (low platelets)" },
      { part: "-phagia, -phagy", meaning: "Eating; Swallowing", example: "Dysphagia (difficulty swallowing)" },
      { part: "-phasia", meaning: "Speech", example: "Aphasia (language impairment)" },
      { part: "-plasia, -plastic", meaning: "Growth", example: "Hyperplasia (increased cell number)" },
      { part: "-plegia", meaning: "Paralysis", example: "Hemiplegia (one-sided paralysis)" },
      { part: "-pnea", meaning: "Breathing", example: "Sleep apnea (breathing pauses during sleep)" },
      { part: "-poiesis", meaning: "Production", example: "Hemopoiesis (blood cell production)" },
      { part: "-ptosis", meaning: "Falling; Drooping", example: "Apoptosis (programmed cell death)" },
      { part: "-rrhage, -rrhagic", meaning: "Bleeding", example: "Hemorrhage (heavy bleeding)" },
      { part: "-rrhea", meaning: "Flow or discharge", example: "Diarrhea (loose stools)" },
      { part: "-sclerosis", meaning: "Hardening", example: "Arteriosclerosis (artery hardening)" },
      { part: "-sis", meaning: "Condition", example: "Agranulocytosis (very low granulocytes)" },
      { part: "-stasis", meaning: "Level; Unchanging", example: "Homeostasis (stable internal state)" },
      { part: "-trophy", meaning: "Growth", example: "Hypertrophy (tissue enlargement)" },
      { part: "-uria", meaning: "In the urine", example: "Anuria (no urine)" }
    ],

    "Procedure Suffixes": [
      { part: "-centesis", meaning: "Surgical puncture to remove fluid", example: "Thoracentesis (drain chest fluid)" },
      { part: "-desis", meaning: "Surgical binding", example: "Pleurodesis (fuse pleural layers)" },
      { part: "-ectomy", meaning: "Cut out; Removal", example: "Mastectomy (breast removal)" },
      { part: "-gram", meaning: "Record; Picture", example: "Electrocardiogram (heart tracing)" },
      { part: "-graph", meaning: "Instrument used to create a record or picture", example: "Electrocardiograph (ECG machine)" },
      { part: "-graphy", meaning: "To record or take a picture", example: "Echocardiography (heart ultrasound)" },
      { part: "-meter", meaning: "Device used for measuring", example: "Sphygmomanometer (blood pressure cuff)" },
      { part: "-opsy", meaning: "Visual examination", example: "Biopsy (tissue sample exam)" },
      { part: "-ostomy", meaning: "Opening", example: "Colostomy (colon opening)" },
      { part: "-otomy", meaning: "Incision", example: "Laparotomy (abdominal incision)" },
      { part: "-pexy", meaning: "Surgical fixation", example: "Oophoropexy (ovary fixation)" },
      { part: "-plasty", meaning: "Surgical reconstruction", example: "Vertebroplasty (vertebra repair)" },
      { part: "-scope", meaning: "For examining", example: "Endoscope (viewing instrument)" },
      { part: "-scopy", meaning: "Examine", example: "Endoscopy (scope exam)" }
    ]
  }
};


// convenience arrays for quiz
window.TERMS_ALL_PREFIXES = Object.values(window.TERMS.prefixes).flat();
window.TERMS_ALL_SUFFIXES = Object.values(window.TERMS.suffixes).flat();
window.TERMS_ALL = [...window.TERMS_ALL_PREFIXES, ...window.TERMS_ALL_SUFFIXES];
